# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'churn.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(900, 900)
        Form.setMaximumSize(QtCore.QSize(900, 900))
        Form.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 14pt \"Comic Sans MS\";\n"
"color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(180, 200, 121, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 270, 221, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(150, 340, 201, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(60, 400, 261, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(50, 470, 251, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(50, 540, 241, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(90, 610, 231, 41))
        self.label_7.setObjectName("label_7")
        self.tenure = QtWidgets.QLineEdit(Form)
        self.tenure.setGeometry(QtCore.QRect(300, 200, 501, 51))
        self.tenure.setObjectName("tenure")
        self.phoneservice = QtWidgets.QComboBox(Form)
        self.phoneservice.setGeometry(QtCore.QRect(300, 270, 501, 41))
        self.phoneservice.setObjectName("phoneservice")
        self.phoneservice.addItem("")
        self.phoneservice.setItemText(0, "")
        self.phoneservice.addItem("")
        self.phoneservice.addItem("")
        self.contract = QtWidgets.QComboBox(Form)
        self.contract.setGeometry(QtCore.QRect(300, 340, 501, 41))
        self.contract.setObjectName("contract")
        self.contract.addItem("")
        self.contract.setItemText(0, "")
        self.contract.addItem("")
        self.contract.addItem("")
        self.contract.addItem("")
        self.billing = QtWidgets.QComboBox(Form)
        self.billing.setGeometry(QtCore.QRect(290, 410, 511, 41))
        self.billing.setObjectName("billing")
        self.billing.addItem("")
        self.billing.setItemText(0, "")
        self.billing.addItem("")
        self.billing.addItem("")
        self.paymethod = QtWidgets.QComboBox(Form)
        self.paymethod.setGeometry(QtCore.QRect(290, 470, 511, 41))
        self.paymethod.setObjectName("paymethod")
        self.paymethod.addItem("")
        self.paymethod.setItemText(0, "")
        self.paymethod.addItem("")
        self.paymethod.addItem("")
        self.paymethod.addItem("")
        self.paymethod.addItem("")
        self.mcharges = QtWidgets.QLineEdit(Form)
        self.mcharges.setGeometry(QtCore.QRect(290, 540, 511, 51))
        self.mcharges.setObjectName("mcharges")
        self.tcharges = QtWidgets.QLineEdit(Form)
        self.tcharges.setGeometry(QtCore.QRect(290, 610, 511, 51))
        self.tcharges.setObjectName("tcharges")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(440, 710, 112, 41))
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(182, 182, 182, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(0, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(70, 800, 241, 31))
        self.label_8.setObjectName("label_8")
        self.churn = QtWidgets.QLineEdit(Form)
        self.churn.setGeometry(QtCore.QRect(300, 790, 511, 51))
        self.churn.setObjectName("churn")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(190, 110, 371, 41))
        self.label_9.setObjectName("label_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Tenure:"))
        self.label_2.setText(_translate("Form", "Phone Service:"))
        self.label_3.setText(_translate("Form", "Contract:"))
        self.label_4.setText(_translate("Form", "Paperless Billing:"))
        self.label_5.setText(_translate("Form", "Payment method:"))
        self.label_6.setText(_translate("Form", "Monthly Charges:"))
        self.label_7.setText(_translate("Form", "Total Charges:"))
        self.phoneservice.setItemText(1, _translate("Form", "No"))
        self.phoneservice.setItemText(2, _translate("Form", "Yes"))
        self.contract.setItemText(1, _translate("Form", "Month-to-month"))
        self.contract.setItemText(2, _translate("Form", "One year"))
        self.contract.setItemText(3, _translate("Form", "Two year"))
        self.billing.setItemText(1, _translate("Form", "Yes"))
        self.billing.setItemText(2, _translate("Form", "No"))
        self.paymethod.setItemText(1, _translate("Form", "Bank transfer (automatic)"))
        self.paymethod.setItemText(2, _translate("Form", "Credit card (automatic)"))
        self.paymethod.setItemText(3, _translate("Form", "Electronic check"))
        self.paymethod.setItemText(4, _translate("Form", "Mailed check"))
        self.pushButton.setText(_translate("Form", "Predict"))
        self.label_8.setText(_translate("Form", "Customer Churn:"))
        self.label_9.setText(_translate("Form", "Customer Churn Prediction"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
