# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'infection.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(815, 662)
        Form.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(225, 225, 225);\n"
"\n"
"\n"
"font: 75 14pt \"Calibri\";")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 50, 321, 41))
        self.label.setStyleSheet("font: 18pt \"HoloLens MDL2 Assets\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(160, 150, 171, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 300, 281, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(80, 350, 241, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(150, 400, 161, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(90, 450, 241, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(250, 200, 68, 31))
        self.label_7.setObjectName("label_7")
        self.feverhrs = QtWidgets.QLineEdit(Form)
        self.feverhrs.setGeometry(QtCore.QRect(310, 150, 371, 41))
        self.feverhrs.setObjectName("feverhrs")
        self.age = QtWidgets.QLineEdit(Form)
        self.age.setGeometry(QtCore.QRect(310, 200, 371, 41))
        self.age.setObjectName("age")
        self.wbc = QtWidgets.QLineEdit(Form)
        self.wbc.setGeometry(QtCore.QRect(310, 300, 371, 41))
        self.wbc.setObjectName("wbc")
        self.pa = QtWidgets.QLineEdit(Form)
        self.pa.setGeometry(QtCore.QRect(310, 350, 371, 41))
        self.pa.setObjectName("pa")
        self.pro = QtWidgets.QLineEdit(Form)
        self.pro.setGeometry(QtCore.QRect(310, 400, 371, 41))
        self.pro.setObjectName("pro")
        self.crp = QtWidgets.QLineEdit(Form)
        self.crp.setGeometry(QtCore.QRect(310, 450, 371, 41))
        self.crp.setObjectName("crp")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(370, 520, 112, 34))
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(120, 590, 171, 31))
        self.label_8.setObjectName("label_8")
        self.type = QtWidgets.QLineEdit(Form)
        self.type.setGeometry(QtCore.QRect(300, 590, 361, 41))
        self.type.setObjectName("type")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(260, 260, 68, 19))
        self.label_9.setObjectName("label_9")
        self.sex = QtWidgets.QLineEdit(Form)
        self.sex.setGeometry(QtCore.QRect(310, 250, 371, 41))
        self.sex.setObjectName("sex")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Infection Prediction"))
        self.label_2.setText(_translate("Form", "Fever Hours:"))
        self.label_3.setText(_translate("Form", "White blood cell count:"))
        self.label_4.setText(_translate("Form", "Previous Antbiotics:"))
        self.label_5.setText(_translate("Form", "Procalcitonin:"))
        self.label_6.setText(_translate("Form", "C-Reactive protein:"))
        self.label_7.setText(_translate("Form", "Age:"))
        self.pushButton.setText(_translate("Form", "Predict"))
        self.label_8.setText(_translate("Form", "Infection Type:"))
        self.label_9.setText(_translate("Form", "Sex:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
